BTC:
  outputs:
    dev:
      account: KYXRWKG-FJ17899
      database: BTC
      password: Sivaprabakaran@#0437
      role: ACCOUNTADMIN
      schema: DBT_BTC
      threads: 1
      type: snowflake
      user: Sivaprabakaran
      warehouse: BTC_WH
    prod:
      account: KYXRWKG-FJ17899
      database: BTC
      password: Sivaprabakaran@#0437
      role: ACCOUNTADMIN
      schema: PROD
      threads: 1
      type: snowflake
      user: Sivaprabakaran
      warehouse: BTC_WH
  target: dev
ITGC:
  outputs:
    dev:
      account: YTRQXAG-KP40275
      database: ITGC
      password: MonkeyDluffy@#2305
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: Sivaprabakaran
      warehouse: ITGC
  target: dev
aws_dbt_snowflake_project:
  outputs:
    dev:
      account: YTRQXAG-KP40275
      database: AIRBNB
      password: MonkeyDluffy@#2305
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: Sivaprabakaran
      warehouse: AIRBNB
  target: dev
